### ISSUE TITLE
Gem breaks devise

### ISSUE THREAD

**Issue by jeremiahlukus** [tobiasbhn/embed-me#1]
Simply adding the gem to the gem file breaks devise.
 
 
 
 ```
 NoMethodError in Devise::SessionsController#new
undefined method `authenticate?' for nil:NilClass

     def constraints_for(method_to_apply, scope = nil, block = nil)
        constraint = lambda do |request|
     ~>     request.env['warden'].send(method_to_apply, scope: scope) &&
            (block.nil? || block.call(request.env["warden"].user(scope)))
        end
```

If you have any ideas why this is happening i wouldn't mind sending a PR

**Comment by jeremiahlukus** [comment]
```
NoMethodError (undefined method `authenticate?' for nil:NilClass):

devise (4.7.3) lib/devise/rails/routes.rb:479:in `block in constraints_for'
actionpack (6.1.3.1) lib/action_dispatch/routing/mapper.rb:42:in `block in matches?'
actionpack (6.1.3.1) lib/action_dispatch/routing/mapper.rb:40:in `all?'
actionpack (6.1.3.1) lib/action_dispatch/routing/mapper.rb:40:in `matches?'
actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:871:in `block in recognize_path_with_request'
actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:74:in `block in recognize'
actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:66:in `each'
actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:66:in `recognize'
actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:861:in `recognize_path_with_request'
actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:857:in `recognize_path'
embed-me (1948ca4e3aab) lib/embed_me/engine.rb:29:in `embedded?'
embed-me (1948ca4e3aab) lib/embed_me/engine.rb:17:in `check_embedding!'
activesupport (6.1.3.1) lib/active_support/callbacks.rb:427:in `block in make_lambda'
activesupport (6.1.3.1) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
actionpack (6.1.3.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (6.1.3.1) lib/active_support/callbacks.rb:199:in `block in halting'
activesupport (6.1.3.1) lib/active_support/callbacks.rb:512:in `block in invoke_before'
activesupport (6.1.3.1) lib/active_support/callbacks.rb:512:in `each'
activesupport (6.1.3.1) lib/active_support/callbacks.rb:512:in `invoke_before'
activesupport (6.1.3.1) lib/active_support/callbacks.rb:115:in `block in run_callbacks'
actiontext (6.1.3.1) lib/action_text/rendering.rb:20:in `with_renderer'
```


So this is getting called for some reason 

```
embed-me (1948ca4e3aab) lib/embed_me/engine.rb:29:in `embedded?'
embed-me (1948ca4e3aab) lib/embed_me/engine.rb:17:in `check_embedding!'
```

**Comment by tobiasbhn** [comment]
I am currently not at Home, but I will take a look into that Issue. I will come back to you within the the next 4 to 6 Hours. In the mean time, could you please provide steps to reproduce the Error in a clean Project?

**Comment by jeremiahlukus** [comment]
https://github.com/jeremiahlukus/embed-me/blob/master/lib/embed_me/engine.rb#L29  

I fixed it on my fork ` path = Rails.application.routes.recognize_path(request.path)`  was causing the issue. Since any error should result in false i just put it in a rescue block.
